"""Static checks for the generated real-time-ecs notebook.

The notebook is regenerated by `scripts/build_notebook.py`. These tests pin
behavior that's easy to silently regress:

1. The ALB ListenerRule priority is derived deterministically (md5, NOT
   Python's randomized `hash()`), so two notebook runs in different
   processes produce the same priority for the same model. Without this,
   re-running the deploy in a fresh shell would create a new rule instead
   of updating the existing one.
2. The 3 supported real-time models (qwen3_8b, medgemma_27b,
   llama_4_scout_17b) hash to distinct priorities so they don't collide
   when deployed on the same ALB.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

NB_PATH = Path(__file__).resolve().parents[1] / "notebooks" / "real-time-ecs.ipynb"


def _priority(model_name: str) -> int:
    """Mirror the formula the notebook uses."""
    # Non-security identifier-derivation use of MD5; usedforsecurity=False
    # tells static scanners the cryptographic strength does not matter here.
    digest = hashlib.md5(model_name.encode(), usedforsecurity=False).hexdigest()
    return 100 + (int(digest, 16) % 900)


def test_notebook_uses_md5_for_priority_not_python_hash():
    """Python's built-in hash() is randomized per-process via PYTHONHASHSEED;
    the notebook must use md5 (or another stable hash) so re-runs in a fresh
    shell update the existing ListenerRule instead of recreating it."""
    raw = NB_PATH.read_text()
    assert "hashlib" in raw, "expected stable hash for listener priority"
    # Must NOT use the built-in hash() for this purpose:
    assert "abs(hash(SERVICE.model_name)) % 900" not in raw


def test_priority_distinct_for_three_realtime_models():
    """The 3 real-time-ready models must hash to distinct ListenerRule
    priorities so deploys to the same ALB don't collide."""
    priorities = {
        "qwen3-8b": _priority("qwen3-8b"),
        "medgemma-27b": _priority("medgemma-27b"),
        "llama-4-scout": _priority("llama-4-scout"),
    }
    assert len(set(priorities.values())) == 3, priorities


def test_priority_in_valid_alb_range():
    """ALB ListenerRule priority must be 1-50000."""
    for name in ["qwen3-8b", "medgemma-27b", "llama-4-scout"]:
        p = _priority(name)
        assert 1 <= p <= 50000, f"{name}: priority {p} out of range"


def test_notebook_path_prefix_default_is_wildcard_aware():
    """The notebook's path_prefix should still be '/*' (matches OpenAI-style
    routes), and there should be a markdown note about needing distinct paths
    when multi-model on one ALB."""
    nb = json.loads(NB_PATH.read_text())
    sources = []
    for cell in nb["cells"]:
        sources.append("".join(cell.get("source", [])))
    blob = "\n".join(sources)
    assert 'path_prefix="/*"' in blob
    # Multi-model warning present:
    assert "non-overlapping path" in blob or "different priority" in blob


def test_notebook_litellm_master_key_has_sk_prefix():
    """LiteLLM enforces master_key starts with 'sk-' at proxy startup; without
    the prefix the proxy aborts with `master_key must start with 'sk-'`. The
    notebook generates the key into Secrets Manager — must include the
    prefix."""
    nb = json.loads(NB_PATH.read_text())
    blob = "\n".join("".join(cell.get("source", [])) for cell in nb["cells"])
    # The literal token-generation line must produce a key with sk- prefix.
    assert '"sk-" + _secrets.token_urlsafe' in blob, (
        "LITELLM_KEY must be prefixed with 'sk-' so LiteLLM accepts it as "
        "master_key (otherwise the proxy refuses to start)"
    )


def test_notebook_threads_alb_certificate_arn_to_networking_stack():
    """The networking stack accepts an optional ``AlbCertificateArn`` to
    create an HTTPS:443 listener; without that param being passed by the
    notebook, supplying a cert is impossible and the router's HTTPS path
    is unreachable end-to-end. The notebook must expose a configuration
    knob (``ALB_CERTIFICATE_ARN``) AND pass it through to the networking
    stack's parameters block.
    """
    nb = json.loads(NB_PATH.read_text())
    blob = "\n".join("".join(cell.get("source", [])) for cell in nb["cells"])
    assert "ALB_CERTIFICATE_ARN" in blob, (
        "notebook must expose a knob to set AlbCertificateArn"
    )
    # Must be a parameter to the networking deploy_stack call:
    assert '"AlbCertificateArn"' in blob and "ALB_CERTIFICATE_ARN" in blob, (
        "ALB_CERTIFICATE_ARN must be passed as the AlbCertificateArn param "
        "to the networking deploy_stack call"
    )


def test_notebook_couples_listener_protocol_to_certificate_arn():
    """The router stack's listener_protocol must match the listener that
    networking actually created. If a cert ARN is set, networking creates
    HTTPS:443 and the router must attach to HTTPS; if empty, both must
    stay on HTTP. Without this coupling, a user supplying a cert ARN
    silently ends up on HTTP (or vice-versa), with the rule attached to
    the wrong listener — an undebuggable 404 from the wrong listener's
    default action.
    """
    nb = json.loads(NB_PATH.read_text())
    blob = "\n".join("".join(cell.get("source", [])) for cell in nb["cells"])
    # The notebook derives LISTENER_PROTOCOL from ALB_CERTIFICATE_ARN.
    assert 'LISTENER_PROTOCOL = "HTTPS" if ALB_CERTIFICATE_ARN else "HTTP"' in blob
    # The router call passes that variable through.
    assert "listener_protocol=LISTENER_PROTOCOL" in blob


def test_notebook_uses_alb_scheme_for_client_calls():
    """Smoke + load test cells must use the actual scheme of the ALB
    listener (http vs https). Hard-coding ``http://`` would break HTTPS
    deploys (curl would land on the wrong port), and hard-coding
    ``https://`` would break cert-less smoke runs."""
    nb = json.loads(NB_PATH.read_text())
    blob = "\n".join("".join(cell.get("source", [])) for cell in nb["cells"])
    assert 'f"{ALB_SCHEME}://{ALB_DNS}"' in blob
    # And no leftover hard-coded http://{ALB_DNS} URLs:
    assert "http://{ALB_DNS}" not in blob, (
        "hard-coded http://{ALB_DNS} would break HTTPS deploys"
    )


def test_notebook_passes_long_wait_timeout_for_llama_scout_model_stack():
    """The 20-vllm-model.yaml stack holds AWS::ECS::Service in
    CREATE_IN_PROGRESS until one task is running and stable. For
    Llama-4-Scout (218 GiB BF16 weights, 18-75 min from HF + ~5 min ASG
    provisioning + ~5 min image pull + ~3 min warmup), the worst case is
    ~90 min — so the notebook must pass a wait_timeout_s longer than
    the deployer's 1h default for the 8-GPU plan. Otherwise the boto3
    waiter raises WaiterError while CFN is still creating, leaving the
    user without outputs and a stack still IN_PROGRESS.
    """
    nb = json.loads(NB_PATH.read_text())
    blob = "\n".join("".join(cell.get("source", [])) for cell in nb["cells"])
    # 8-GPU plan must lift the timeout >= 7200s (2h):
    assert "wait_timeout_s=_MODEL_STACK_TIMEOUT_S" in blob, (
        "model stack deploy must pass an explicit wait_timeout_s so the 8-GPU "
        "plan can override the deployer's 1h default"
    )
    assert "_MODEL_STACK_TIMEOUT_S = 7200 if SERVICE.gpu_count >= 8 else 3600" in blob


def test_notebook_passes_root_volume_size_for_llama_scout():
    """The cluster cell must size the root volume up for 8-GPU instances —
    Llama-4-Scout-17B-16E is ~218 GiB BF16 and a 200 GiB default would run
    out of space during model pull."""
    nb = json.loads(NB_PATH.read_text())
    blob = "\n".join("".join(cell.get("source", [])) for cell in nb["cells"])
    assert "RootVolumeSizeGiB" in blob, (
        "cluster deploy must pass RootVolumeSizeGiB so the launch template "
        "provisions enough disk for the model weights"
    )
    # 8-GPU branch must size up to >= 300 GiB.
    assert "400" in blob and "gpu_count >= 8" in blob
