apiVersion: v1
kind: Service
metadata:
  name: @@MASTER_POD@@
  labels:
    app.kubernetes.io/name: @@RUN_NAME@@
spec:
  selector:
    app.kubernetes.io/name: @@RUN_NAME@@
    app.kubernetes.io/component: master
  ports:
    - name: rendezvous
      port: @@MASTER_PORT@@
      targetPort: @@MASTER_PORT@@
